# Generated by Django 5.2 on 2025-04-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0002_combineauth_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CombineAuth',
        ),
    ]
