# Generated by Django 5.2.1 on 2025-05-18 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDjangoAdmin', '0014_libraryuser_otp_code_libraryuser_otp_expiry_and_more'),
        ('myserver', '0005_recentlyviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyviewed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_books', to='myDjangoAdmin.libraryuser'),
        ),
    ]
