# Generated by Django 5.2.1 on 2025-05-18 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDjangoAdmin', '0014_libraryuser_otp_code_libraryuser_otp_expiry_and_more'),
        ('myserver', '0006_alter_recentlyviewed_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_carts', to='myDjangoAdmin.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_cart', to='myDjangoAdmin.libraryuser')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
