# Generated by Django 5.2.1 on 2025-05-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0008_borrowedbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='return_due',
        ),
    ]
