# Generated by Django 5.2.1 on 2025-05-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0010_reservedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedbook',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
