# Generated by Django 5.2.1 on 2025-05-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0011_reservedbook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
