# Generated by Django 5.2.1 on 2025-05-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0012_borrowedbook_returned_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowedbook',
            unique_together=set(),
        ),
    ]
