# Generated by Django 5.2 on 2025-04-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDjangoAdmin', '0002_staff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
