# Generated by Django 5.2 on 2025-04-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myDjangoAdmin', '0006_usersessionlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='LibraryUser',
        ),
        migrations.RenameField(
            model_name='usersessionlog',
            old_name='user',
            new_name='libraryUser',
        ),
    ]
