# Generated by Django 5.2 on 2025-04-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDjangoAdmin', '0007_rename_user_libraryuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersessionlog',
            old_name='libraryUser',
            new_name='library_user',
        ),
    ]
