# Generated by Django 5.2.1 on 2025-05-11 12:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDjangoAdmin', '0008_rename_libraryuser_usersessionlog_library_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_extra_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('publisher', models.CharField(max_length=255)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('copies', models.PositiveIntegerField()),
                ('cover_image', models.ImageField(upload_to='book_covers/')),
                ('barcode_code', models.CharField(max_length=100, unique=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='book_barcodes/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_images', models.ManyToManyField(blank=True, to='myDjangoAdmin.bookimage')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myDjangoAdmin.genre')),
            ],
        ),
    ]
