# Generated by Django 5.2.1 on 2025-05-11 12:56

from django.db import migrations

def add_genres(apps, schema_editor):
    Genre = apps.get_model('myDjangoAdmin', 'Genre')
    genres = [
        'Computer Science', 'Knowledge & Systems', 'Bibliographies', 
        'Information Sciences', 'Encyclopedias', 'Books of Facts', 
        'Magazines & Journals', 'Journalism & Publishing', 'Manuscripts & Rare Books', 
        'Philosophy & Psychology', 'Religion', 'Social Sciences', 'Science', 
        'Technology', 'Medicine & Health', 'Engineering', 'Agriculture', 
        'Architecture', 'Graphic Arts & Decorative Arts', 'Arts & Recreation', 
        'Literature', 'History & Geography', 'Astronomy', 'Earth Sciences & Geology', 
        'Biology', 'Fossils & Prehistoric Life', 'Economics', 'Computer Programming', 
        'Mathematics', 'Mythology'
    ]
    for genre_name in genres:
        Genre.objects.get_or_create(name=genre_name)

class Migration(migrations.Migration):

    dependencies = [
        ('myDjangoAdmin', '0010_remove_book_genre_book_genres'),
    ]

    operations = [
        migrations.RunPython(add_genres),
    ]
