# Generated by Django 5.2.1 on 2025-05-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDjangoAdmin', '0011_add_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='extra_images',
        ),
        migrations.AddField(
            model_name='book',
            name='extra_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='book_extra_images/'),
        ),
        migrations.AddField(
            model_name='book',
            name='extra_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='book_extra_images/'),
        ),
        migrations.AddField(
            model_name='book',
            name='extra_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='book_extra_images/'),
        ),
        migrations.AddField(
            model_name='book',
            name='extra_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='book_extra_images/'),
        ),
        migrations.AddField(
            model_name='book',
            name='extra_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='book_extra_images/'),
        ),
        migrations.DeleteModel(
            name='BookImage',
        ),
    ]
