# Generated by Django 5.2.1 on 2025-05-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDjangoAdmin', '0013_remove_book_genres_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryuser',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libraryuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
